os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '10'
  - '8'
env:
  - YARN_GPG=no
cache: yarn
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
